server:
  port: 8085
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covoiturage_auth
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  application:
    name: authentication

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your_default_secret_key_here_minimum_256_bits}
  expiration: 86400000  # 24 hours in milliseconds

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.covoiturage.authentication: DEBUG 